name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Prepare java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu' # https://github.com/actions/setup-java/blob/main/README.md#Supported-distributions
        java-version: '14'
        java-package: jdk # optional (jdk or jre) - defaults to jdk
    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@3.5
      with:
        cli: 1.10.3.929 # Clojure CLI based on tools.deps
    - name: clj-fmt
      if: ${{ matrix.os != 'windows-latest' }}
      run: clojure -M:cljfmt
      shell: bash
    - name: clj-kondo
      run: clojure -M:lint
    - name: clj-test
      run: clojure -M:test
    - name: Release
      if: success()
      # if: github.event_name == 'push'
      env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        CODECOV_TOKEN: ${{ secrets.CodecovToken }}
      run: |
        git config --global user.email "andreas.wolfgang.bauer@gmail.com"
        git config --global user.name "awb99"
        clojure -T:build jar 
        clojure -T:build deploy